### PR TITLE
move to sbt 1. don't support or publish for 0.13 anymore

### LINKED ISSUE #32: support sbt 1.x
practice what we preach

### PR DESCRIPTION
**Pull request by SethTisue**
fixes #32

### CODE REVIEW

**Comment by SethTisue** [comment]
this first commit doesn't have any code changes yet, just build changes. setting a baseline.

**Comment by dwijnand** [comment]
GTG for me (if it goes green).

**Comment by SethTisue** [comment]
thank you Dale, that's a big timesaver

**Comment by SethTisue** [comment]
gah, I targeted the wrong branch. I'll fix it with force-pushes

**Pull request merged**
