### PR TITLE
Add sbt-version-policy

### PR DESCRIPTION
**Pull request by julienrf**
See https://github.com/scala/scala-library-next/pull/93#issuecomment-887812682

However, I have a few issues:
- there are no tests
- I’m not sure about the fact that these settings are assigned to the root project only

### CODE REVIEW

**Comment by SethTisue** [comment]
This looks plausible to me. We can always revise after we have some experience with it in the actual module repos.

**Review by SethTisue — APPROVED** [review]

**Comment by julienrf** [comment]
Let me try it locally on a few modules before we merge it.

**Comment by julienrf** [comment]
OK, this looks good to me. We have to take care of the correct scoping of the settings, but it works. Could you please release 2.4.0 after it is merged?

**Comment by SethTisue** [comment]
* release notes: https://github.com/scala/sbt-scala-module/releases/tag/v2.4.0
* release job: https://travis-ci.com/github/scala/sbt-scala-module/builds/234391865

should be on its way to Maven Central

**Pull request merged**
